-- create database name school
CREATE DATABASE SCHOOL;



-- selecting database
USE SCHOOL;


-- CREATING TABLE 
CREATE TABLE STUDENTS(
	ID INT, 
    NAME VARCHAR(40),
    CLASS int
);

-- CHECK DESCRIPRICTION OF A TABLE 
DESCRIBE STUDENTS;

INSERT INTO STUDENTS(ID, NAME, CLASS) 
VALUES(101,'RAVI', 9), (101,'RAVI', 9);

SELECT * FROM STUDENTS;
